import { createClient } from "@supabase/supabase-js";
import crypto from "node:crypto";
import fs from "node:fs";

const SUPABASE_URL = process.env.SUPABASE_URL;
const SERVICE_ROLE_KEY = process.env.SUPABASE_SERVICE_ROLE_KEY;

if (!SUPABASE_URL || !SERVICE_ROLE_KEY) {
  console.error("Set SUPABASE_URL and SUPABASE_SERVICE_ROLE_KEY first.");
  process.exit(1);
}

const supabase = createClient(SUPABASE_URL, SERVICE_ROLE_KEY, {
  auth: { autoRefreshToken:false, persistSession:false }
});

const accounts = [
  ["Andre Rizki Juanda","andre@karsa.id","director","Operasional","Director"],
  ["Johannes Betrand S. Pardosi","johannes@karsa.id","general_manager","Operasional","General Manager"],
  ["Muhammad Hasan Niam","hasan@karsa.id","operational_head","Operasional","Head Divisi Operasional"],
  ["Andreas","andreas@karsa.id","division_head","Finance","Head Divisi Finance"],
  ["Rizqia Febrianoor","rizqia@karsa.id","staff","Finance","Staff Finance"],
  ["Dimas Putra Pratama","dimas@karsa.id","division_head","IT","Head Divisi IT"],
  ["Vicky Ferdiansyah","vicky@karsa.id","staff","IT","Staff IT"],
  ["Alif","alif@karsa.id","division_head","R&D","Head Divisi R&D"],
  ["Muslimin","muslimin@karsa.id","staff","R&D","Staff R&D"],
  ["Reja Maulana","reja@karsa.id","staff","R&D","Staff R&D"],
  ["Peter Vincent Kusuma","peter@karsa.id","staff","Operasional","Staff Operasional"]
];

function password(){
  return "Karsa!" + crypto.randomBytes(7).toString("base64url") + "9";
}

const result = [];
for (const [name,email,role,division,title] of accounts) {
  const tempPassword = password();
  const {data,error} = await supabase.auth.admin.createUser({
    email, password:tempPassword, email_confirm:true,
    user_metadata:{name,role,division,title}
  });

  if (error) {
    console.error(`FAILED ${email}: ${error.message}`);
    continue;
  }

  const {error:profileError} = await supabase.from("profiles").upsert({
    id:data.user.id,name,email,role,division,title
  });

  if (profileError) {
    console.error(`PROFILE FAILED ${email}: ${profileError.message}`);
    continue;
  }

  result.push({name,email,role,division,tempPassword});
  console.log(`CREATED ${email}`);
}

fs.writeFileSync("initial-credentials.json", JSON.stringify({
  generated_at:new Date().toISOString(),
  warning:"Temporary passwords. Change them after first login."
}, null, 2));

const lines = [
  "KARSA INITIAL CREDENTIALS",
  "Generated by provision-users.mjs",
  "",
  ...result.map(x=>`${x.name} | ${x.email} | ${x.role} | ${x.division} | TEMP PASSWORD: ${x.tempPassword}`)
];
fs.writeFileSync("initial-credentials.txt", lines.join("\n"));

console.log("\nCreated:", result.length, "accounts");
console.log("Credentials saved to initial-credentials.txt");
console.log("Keep that file private and delete it after passwords are distributed.");
